create table if not exists meetings
(
    id         integer generated by default as identity
        constraint meetings_pk
            primary key,
    name       varchar(50) not null,
    owner      varchar(50) not null,
    start_date timestamp   not null,
    end_date   timestamp   not null
);